services:
    sisconis-db:
        image: postgres:16-alpine
        container_name: sisconis-db
        restart: unless-stopped
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - '5432:5432'
        volumes:
            - sisconis-db-data:/var/lib/postgresql/data
        networks:
            - sisconis-net
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres -d sisconis']
            interval: 10s
            timeout: 5s
            retries: 5

    sisconis-redis:
        image: redis:7-alpine
        container_name: sisconis-redis
        restart: unless-stopped
        command: redis-server --aclfile /usr/local/etc/redis/users.acl
        ports:
            - '6379:6379'
        volumes:
            - sisconis-redis-data:/data
            - ./redis/users.acl:/usr/local/etc/redis/users.acl:ro
        networks:
            - sisconis-net
        healthcheck:
            test: ['CMD', 'redis-cli', '--user', 'sisconis', '--pass', '${REDIS_PASSWORD}', '--no-auth-warning', 'ping']
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    sisconis-db-data:
        name: sisconis-db-data
    sisconis-redis-data:
        name: sisconis-redis-data

networks:
    sisconis-net:
